version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile

    #   ##protip: args:
    #     ENV: dev        #  Build-time argument
    # environment:
    #   ENV: dev          # Runtime environment variable


    container_name: fastapi-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - app-network
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-app
    ports:
      - "5173:5173"
    networks:
      - app-network
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
